apiVersion: 1

datasources:
  # Prometheus datasource for JVM metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s

  # InfluxDB v2 datasource for JMeter metrics
  - name: InfluxDB_JMeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    jsonData:
      version: Flux
      organization: perf
      defaultBucket: jmeter
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
